### PR TITLE
Update dxvk.git to 2.2

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
One more issue:

```
]2;flatpak-builder: Post-Install dxvkFB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/dxvk --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64-5/build/.flatpak-builder/build/dxvk-1 --bind-mount=/run/build/dxvk=/srv/buildbot/worker/build-x86_64-5/build/.flatpak-builder/build/dxvk-1 --build-dir=/run/build/dxvk/_flatpak_build --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-5/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1689528551 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer  -fno-stack-clash-protection' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer  -fno-stack-clash-protection' --env=LDFLAGS= --env=SUFFIX= --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/dlls/dxvk/bin:/app/bin:/usr/bin:/usr/lib/sdk/mingw-w64/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=64 /srv/buildbot/worker/build-x86_64-5/build/.flatpak-builder/rofiles/rofiles-jH5EvN /bin/sh -c 'set -e
for lib in dxgi d3d9 d3d10 d3d10core d3d10_1 d3d11; do
  winebuild --builtin ${FLATPAK_DEST}/lib${SUFFIX}/$lib.dll
done
'' on host
Cannot open /app/dlls/dxvk/lib/d3d10.dll : No such file or directory
FB: host_command_exited_cb 1523859 256
```

**Comment by AsciiWolf** [comment]
This is the build config:

```
dxvk v2.2
  Subprojects
    libdisplay-info: YES
  User defined options
    Cross files    : ../build-win64.txt
                     ../dxvk-ccache-win64.txt
    bindir         : lib
    buildtype      : release
    libdir         : lib
    prefix         : /app/dlls/dxvk
    strip          : True
    enable_d3d10   : true
    enable_d3d11   : true
    enable_d3d9    : true
    enable_dxgi    : true
```

Everything looks fine, but only `d3d10core.dll` gets installed, not `d3d10.dll`.

@gasinvein Any idea? Was `d3d10.dll` removed from DXVK?

**Comment by AsciiWolf** [comment]
Ah, I will answer my own question. It was removed and replaced by `d3d10core.dll`: https://github.com/doitsujin/dxvk/pull/2881

**Comment by AsciiWolf** [comment]
"D3D10_1.dll is provided by Wine."

So only d3d10core.dll should be needed.

**Comment by AsciiWolf** [comment]
It looks like that exe file are also not part of DXVK anymore. I have removed these two lines from the build manifest:

```
      - mkdir -p ${FLATPAK_DEST}/bin${SUFFIX}
      - mv -v ${FLATPAK_DEST}/lib${SUFFIX}/*.exe ${FLATPAK_DEST}/bin${SUFFIX}/
```

**Comment by AsciiWolf** [comment]
@gasinvein Feel free to test and/or merge.

**Comment by gasinvein** [comment]
Thanks!

**Pull request merged**
